[package]
name = "avent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
anyhow = "1.0.51"
humantime = "2.1.0"
owo-colors = "3.2.0"
